apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway
spec:
  rules:
  - host: gateway.192.168.0.9.nip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: gateway
          servicePort: 32004
---
kind: Service
apiVersion: v1
metadata:
  name: gateway
spec:
  type: NodePort
  selector:
    app: spring-cloud-gateway
  ports:
  - protocol: TCP
    port: 9001
    targetPort: 9001
    nodePort: 32004
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-cloud-gateway
  labels:
    app: spring-cloud-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-cloud-gateway
  template:
    metadata:
      labels:
        app: spring-cloud-gateway
        version: latest
    spec:
      hostname: gateway
      subdomain: gateway
      containers:
      - name: spring-cloud-gateway
        image: 192.168.0.8:5000/spring-cloud-gateway:latest
        ports:
        - name: http
          containerPort: 9001
